modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/SuperMultiDrills/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/super-multi-drills"
#logoFile="examplemod.png" #optional
credits=""
authors="SilentChaos512"

[[mods]]
    modId="supermultidrills"
    version="${file.jarVersion}"
    displayName="Super Multi-Drills"
#    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SuperMultiDrills/1.15/update.json"
    description='''
    Downloads: https://www.curseforge.com/minecraft/mc-mods/super-multi-drills (I do not upload anywhere else)
    Changelog: https://github.com/SilentChaos512/SuperMultiDrills/blob/1.16.x/CHANGELOG.md
    Source: https://github.com/SilentChaos512/SuperMultiDrills/
    Issues: https://github.com/SilentChaos512/SuperMultiDrills/issues
    '''

[[dependencies.supermultidrills]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.supermultidrills]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.supermultidrills]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.supermultidrills]]
    modId="silentgear"
    mandatory=true
    versionRange="[2.4,)"
    ordering="AFTER"
    side="BOTH"