@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.supermultidrills.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;